COLUMNS:
  MedInc: float64
  HouseAge: float64
  AveRooms: float64
  AveBedrms: float64
  Population: float64
  AveOccup: float64
  Latitude: float64
  Longitude: float64
  MedHouseValue: float64

TARGET_COLUMN:
  name: MedHouseValue
