name: Auto Deploy on Push

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: california-api
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          pip install -r requirements.txt
          pip install flake8
          flake8 . --max-line-length=120 --exclude=artifacts,.github,__pycache__

  docker:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: docker build -t $DOCKER_USER/$IMAGE_NAME:latest .
      - run: docker push $DOCKER_USER/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} \
          "DOCKER_USER=$DOCKER_USER IMAGE_NAME=$IMAGE_NAME bash -s" < ./deploy.sh
